# Generated by Django 4.2.1 on 2023-05-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MessageBoard", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
