# Generated by Django 4.2.1 on 2023-05-08 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MessageBoard", "0004_userprofile_alter_comment_author_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="username",
        ),
        migrations.RemoveField(
            model_name="post",
            name="username",
        ),
    ]
